### ISSUE TITLE
Exception when using camel-jfr in timer-http

### ISSUE THREAD

**Issue by Croway** [apache/camel-performance-tests#70]
Hi @davsclaus, @oscerd, I tried to add camel-jfr dependency in timer-http, executing `mvn camel:run` it is working as expected, but I'm getting an exception (warning) during camel shutdown:

```
13:17:48.062 [org.apache.camel.example.MyApplication.main()] INFO  o.a.c.i.engine.AbstractCamelContext - Apache Camel 3.14.0-SNAPSHOT (MyTinyCamel) shutting down (timeout:45s)
13:17:48.069 [Camel (MyTinyCamel) thread #3 - ShutdownTask] INFO  o.a.c.i.e.DefaultShutdownStrategy - Waiting as there are still 1 inflight and pending exchanges to complete, timeout in 45 seconds. Inflights per route: [route1 = 1]
13:17:49.070 [Camel (MyTinyCamel) thread #3 - ShutdownTask] INFO  o.a.c.i.engine.PooledExchangeFactory - PooledExchangeFactory route1 (timer://foo) usage [pooled: 1, created: 1, acquired: 0 released: 1, discarded: 0]
13:17:49.074 [org.apache.camel.example.MyApplication.main()] INFO  o.a.c.i.engine.AbstractCamelContext - Routes stopped (total:1 stopped:1)
13:17:49.074 [org.apache.camel.example.MyApplication.main()] INFO  o.a.c.i.engine.AbstractCamelContext -     Stopped route1 (timer://foo)
13:17:49.077 [org.apache.camel.example.MyApplication.main()] INFO  o.a.c.i.engine.AbstractCamelContext - Apache Camel 3.14.0-SNAPSHOT (MyTinyCamel) shutdown in 1s15ms (uptime:11s62ms)
java.lang.InterruptedException
	at java.base/java.lang.Object.wait(Native Method)
	at jdk.jfr/jdk.jfr.internal.PlatformRecorder.takeNap(PlatformRecorder.java:448)
	at jdk.jfr/jdk.jfr.internal.PlatformRecorder.periodicTask(PlatformRecorder.java:441)
	at jdk.jfr/jdk.jfr.internal.PlatformRecorder.lambda$startDiskMonitor$1(PlatformRecorder.java:386)
	at java.base/java.lang.Thread.run(Thread.java:834)
[WARNING] thread Thread[JFR Periodic Tasks,5,org.apache.camel.example.MyApplication] was interrupted but is still alive after waiting at least 15000msecs
[WARNING] thread Thread[JFR Periodic Tasks,5,org.apache.camel.example.MyApplication] will linger despite being asked to die via interruption
[WARNING] thread Thread[JFR Recording Scheduler,5,org.apache.camel.example.MyApplication] will linger despite being asked to die via interruption
[WARNING] NOTE: 2 thread(s) did not finish despite being asked to  via interruption. This is not a problem with exec:java, it is a problem with the running code. Although not serious, it should be remedied.
[WARNING] Couldn't destroy threadgroup org.apache.camel.maven.RunMojo$IsolatedThreadGroup[name=org.apache.camel.example.MyApplication,maxpri=10]
```

build ends successfully and the jfr file is created as expected, I just wanted to report this since timer-log executes without the exception.

**Comment by oscerd** [comment]
Thanks for reporting.

**Comment by davsclaus** [comment]
Oh thanks. 

I wonder if its possible to run the example without mvn camel:run, eg via a java -jar or from IDEA to run a main class etc. I am asking because the mvn camel:run is using some old cruft code from mvn exec:exec that is "not clean". So would like to see if there is a difference, that can help pin point the problem.

And what JVM version do you use?

**Comment by Croway** [comment]
You are right, the issue is related to `mvn camel:run`, running the jar or from IDEA works as expected, the exception is thrown with both `openjdk version "11.0.9.1" 2020-11-04` and `openjdk version "1.8.0_292"`.
